# Generated by Django 4.2.2 on 2023-06-23 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo', models.TextField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'tipo_p',
                'verbose_name_plural': 'tipo productos',
                'db_table': 'Tipo de produuctos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_producto', models.CharField(max_length=50, unique=True)),
                ('desc_producto', models.TextField(max_length=500)),
                ('stock_producto', models.IntegerField()),
                ('valor_producto', models.IntegerField()),
                ('id_tipo_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_tipo_1', to='m_productos.tipo_producto')),
                ('id_tipo_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_tipo_2', to='m_productos.tipo_producto')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'Productos',
                'ordering': ['id'],
            },
        ),
    ]
