# Generated by Django 4.2.2 on 2023-06-24 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('m_productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tipo_producto',
            table='Tipo de productos',
        ),
    ]
