# Generated by Django 4.2.2 on 2023-06-24 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m_productos', '0002_alter_tipo_producto_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='img_producto',
            field=models.ImageField(default='pkm imagen', upload_to=''),
        ),
    ]
