# Generated by Django 4.2.2 on 2023-06-24 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m_productos', '0003_producto_img_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_producto',
            name='nombre_tipo',
            field=models.TextField(max_length=50, null=True, unique=True),
        ),
    ]
