# Generated by Django 4.2.2 on 2023-06-24 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m_productos', '0005_alter_tipo_producto_nombre_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='img_producto',
            field=models.ImageField(upload_to='fotos_pkm'),
        ),
        migrations.AlterField(
            model_name='tipo_producto',
            name='nombre_tipo',
            field=models.CharField(max_length=50),
        ),
    ]
