# Generated by Django 4.2.2 on 2023-06-24 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m_productos', '0006_alter_producto_img_producto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='img_producto',
        ),
        migrations.AddField(
            model_name='producto',
            name='portada',
            field=models.ImageField(null=True, upload_to='portada'),
        ),
    ]
