# Generated by Django 4.2.2 on 2023-06-24 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m_productos', '0007_remove_producto_img_producto_producto_portada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='portada',
        ),
        migrations.AddField(
            model_name='producto',
            name='img_producto',
            field=models.ImageField(null=True, upload_to='fotos_pkm'),
        ),
    ]
