# Generated by Django 4.2.2 on 2023-06-24 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m_productos', '0008_remove_producto_portada_producto_img_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='img_producto',
            field=models.ImageField(upload_to='fotos_pkm'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_producto',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='valor_producto',
            field=models.PositiveIntegerField(),
        ),
    ]
