# Generated by Django 4.2 on 2023-07-05 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m_productos', '0009_alter_producto_img_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='img_producto',
            field=models.ImageField(upload_to='recursos/img/fotos_pkm/'),
        ),
    ]
