# Generated by Django 4.2.2 on 2023-06-25 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m_venta', '0002_alter_detalle_venta_options_alter_venta_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='monto_total',
            field=models.IntegerField(default=0),
        ),
    ]
