# Generated by Django 4.2 on 2023-06-30 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('m_comentario', '0002_alter_comentario_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={},
        ),
        migrations.AlterModelTable(
            name='comentario',
            table=None,
        ),
    ]
