# Generated by Django 4.2 on 2023-06-30 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('m_comentario', '0003_alter_comentario_options_alter_comentario_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'ordering': ['id'], 'verbose_name': 'coment', 'verbose_name_plural': 'comentarios'},
        ),
        migrations.AlterModelTable(
            name='comentario',
            table='comentarios',
        ),
    ]
